clean: true
author: Arnaud Schloune
author_url: https://twitter.com/arnaud_momo
github_url: https://github.com/arn00s/cariocamenu
github_file_prefix: 
module: carioca
min_acl: internal
exclude: [
    carioca/AppDelegate.swift
    carioca/DemoControllers/DemoAboutViewController.swift,
    carioca/DemoControllers/DemoIntroViewController.swift,
    carioca/DemoControllers/DemoMapViewController.swift,
    carioca/DemoControllers/DemoSettingsViewController.swift,
    carioca/DemoControllers/DemoViewController.swift,
    carioca/DemoControllers/DemoWebViewController.swift
]
hide_documentation_coverage: false